// Generated by CoffeeScript 1.7.0
(function() {
  var Boss, Modal, boss, game,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Modal = require('./');

  Boss = (function(_super) {
    __extends(Boss, _super);

    function Boss(game, opts) {
      this.game = game;
      this.cover = document.createElement('iframe');
      this.cover.style.visibility = 'hidden';
      this.cover.style.position = 'absolute';
      this.cover.style.top = '100px';
      this.cover.setAttribute('src', 'http://microsoft.com/');
      this.cover.setAttribute('width', '100%');
      this.cover.setAttribute('height', '100%');
      document.body.appendChild(this.cover);
      opts.element = this.cover;
      Boss.__super__.constructor.call(this, game, opts);
    }

    return Boss;

  })(Modal);

  game = require('voxel-hello-world')({
    mesher: require('voxel').meshers.greedy
  });

  boss = new Boss(game, {});

  window.addEventListener('keydown', function(ev) {
    if (ev.keyCode === 'B'.charCodeAt(0)) {
      return boss.open();
    }
  });

}).call(this);
